### ISSUE TITLE
Deleting a node causes errors

### ISSUE THREAD

**Issue by pajtai** [Solid-Interactive/grasshopper-core-nodejs#83]
Saw these errors after deleting a node:

> GET /api/contenttypes 200 - - 871.515 ms
> TypeError: next is not a function
>    at deleteKeys (/Users/dota/my-app/node_modules/grasshopper-core/lib/assets/aws/index.js:358:17)
>    at fn (/Users/dota/my-app/node_modules/grasshopper-core/node_modules/async/lib/async.js:746:34)
>    at /Users/dota/my-app/node_modules/grasshopper-core/node_modules/async/lib/async.js:1213:16
>    at /Users/dota/my-app/node_modules/grasshopper-core/node_modules/async/lib/async.js:166:37
>    at /Users/dota/my-app/node_modules/grasshopper-core/node_modules/async/lib/async.js:706:43
>    at /Users/dota/my-app/node_modules/grasshopper-core/node_modules/async/lib/async.js:167:37
>    at Immediate.<anonymous> (/Users/dota/my-app/node_modules/grasshopper-core/node_modules/async/lib/async.js:1206:34)
>    at runCallback (timers.js:574:20)
>    at tryOnImmediate (timers.js:554:5)
>    at processImmed _immediateCallback] (timers.js:533:5)
>

**Comment by Duder-onomy** [comment]
I think this has to do with another issue which is deleting a node does not delete its content.
